entries:
  - name: "tester"
    factory: "template"
    config:
      in_pattern: "/test-locations/**/res=*.series"
      out_pattern: "test-$0.txt"
#      template_file: ./test.tmpl
      template_file: ./noyo/data.md.tmpl
