entries:
  - name: "tester"
    factory: "template"
    config:
      in_pattern: "/test-locations/**/res=*.series"
      out_pattern: "test-$0.txt"
      template: "HELLO!! Summary: {{ export | to_json }}\n\nTemplate Variables:\n{{ vars | to_json }}"
