# Template factory: generate HTML pages from reduced data
#
# Uses the same pattern as noyo/template.yaml:
#   in_pattern matches reduced series
#   out_pattern uses $0 capture for filenames
#   template_file points to Tera HTML template stored in pond

entries:
  - name: "params"
    factory: "template"
    config:
      in_pattern: "/reduced/single_param/**/*.series"
      out_pattern: "$0.html"
      template_file: "/etc/data.html.tmpl"

  - name: "sites"
    factory: "template"
    config:
      in_pattern: "/reduced/single_site/**/*.series"
      out_pattern: "$0.html"
      template_file: "/etc/data.html.tmpl"

  - name: "index"
    factory: "template"
    config:
      in_pattern: "/reduced/single_*/**/*.series"
      out_pattern: "index.html"
      template_file: "/etc/index.html.tmpl"

  - name: "page"
    factory: "template"
    config:
      in_pattern: "/reduced/single_*/**/*.series"
      out_pattern: "page.html"
      template_file: "/etc/page.html.tmpl"
